# Mice under treatment or not to prolong their survival after invasive surgery.

  # Treatment: 94, 197, 16, 38, 99, 141, 23.

  # Control: 52, 104, 146, 10, 51, 30, 40, 27, 46.

# a) Use Bootstrap techniques to determine if there is a significant difference between the means.
  
# b) Compare the results from part 1 with a standard t-test for comparison of means.

# c) Use Bootstrap techniques to determine if there is a significant difference between the medians.

library(boot)

treatment_data <- c(94, 197, 16, 38, 99, 141, 23) # treatment and control data
control_data <- c(52, 104, 146, 10, 51, 30, 40, 27, 46)

n1 <- length(treatment_data) # sample sizes
n2 <- length(control_data)

c(treatment_data, control_data) # combined data

# Mean Difference

mean_diff <- function(data, i) {
  treatment_sample <- sample(treatment_data, length(treatment_data), replace = TRUE)
  control_sample <- sample(control_data, length(control_data), replace = TRUE) 
  return(mean(treatment_sample) - mean(control_sample))
} 

runs <- 10000
bootstrap <- boot(data = c(treatment_data, control_data), statistic = mean_diff, R = runs) # bootstrap sampling

mean_diff_bootstrap <- mean(bootstrap$t)
mean_diff_bootstrap 

boot.ci(bootstrap, type = 'perc') # confidence interval at 95% significance level

hist(bootstrap$t, breaks = 30, main = 'Mean Difference Distribution',
     xlab = 'Mean Difference', border = 'black')
abline(v = quantile(bootstrap$t, c(0.025, 0.975)), col = 'red', lty = 2)

# t-Test for Mean Difference

t_test_result <- t.test(treatment_data, control_data) # perform a two sample t-test
t_test_result

t_test_result$estimate # mean values of treatment and control data, respectively

t_test_result$estimate[1] - t_test_result$estimate[2] # mean difference t-test

# The difference in means obtained with the bootstrap method is 30.30, while with the t-test it is 30.63. Both estimates are very close, suggesting that both the parametric approach (t-test) and the non-parametric approach (bootstrap) provide consistent results.

# According to the p-value obtained from the t-test, there is not enough evidence to assert that the means of both groups differ from each other (i.e., 0.3155 > alpha). This can be reinforced with the confidence interval generated by the bootstrap method:

  # CI(95%) = (-23.11, 84.08)

# Since the interval includes the value 0, there is a possibility that the difference between the means is equal to 0. Therefore, we cannot conclusively say that there is a difference between the means of both groups.

# Median Difference

median_diff <- function(data, i) {
  treatment_sample <- sample(treatment_data, length(treatment_data), replace = TRUE)
  control_sample <- sample(control_data, length(control_data), replace = TRUE) 
  return(median(treatment_sample) - median(control_sample)) 
}

runs <- 10000
bootstrap <- boot(data = c(treatment_data, control_data), statistic = median_diff, R = runs) # bootstrap sampling

median_diff_bootstrap <- mean(bootstrap$t)
median_diff_bootstrap

boot.ci(bootstrap, type = 'perc') # confidence interval at 95% significance level

# As in the previous case, the interval includes the value 0, so there is a possibility that the difference between the medians is equal to 0. That is, based on the confidence interval, we cannot reject the null hypothesis (H0: mu_1 - mu_2 = 0).

  # CI(95%) = (-29, 101)
